# This workflow will install Python dependencies, run pytests and run notebooks
# then it will in python 3.9 (ubuntu-latest) create a badge with the coverage
# and add it to the PR. This badge will be updated if the PR is updated.

name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    concurrency:
      group: "${{ github.workflow }} @ ${{ github.ref }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ {{ cookiecutter.github_user }} }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/{{ cookiecutter.github_user }}/{{ cookiecutter.project_name }}-devcontainer
          cacheFrom: ghcr.io/{{ cookiecutter.github_user }}/{{ cookiecutter.project_name }}-devcontainer
          push: filter
          refFilterForPush: refs/heads/main
          runCmd:
            make validate
